
import { KanaChar, AlphabetType, KanaGroup } from './types';

const HIRAGANA_BASIC: KanaChar[] = [
  { char: 'あ', romaji: 'a', row: 'vowel', type: AlphabetType.HIRAGANA, group: KanaGroup.HIRAGANA_BASIC },
  { char: 'い', romaji: 'i', row: 'vowel', type: AlphabetType.HIRAGANA, group: KanaGroup.HIRAGANA_BASIC },
  { char: 'う', romaji: 'u', row: 'vowel', type: AlphabetType.HIRAGANA, group: KanaGroup.HIRAGANA_BASIC },
  { char: 'え', romaji: 'e', row: 'vowel', type: AlphabetType.HIRAGANA, group: KanaGroup.HIRAGANA_BASIC },
  { char: 'お', romaji: 'o', row: 'vowel', type: AlphabetType.HIRAGANA, group: KanaGroup.HIRAGANA_BASIC },
  { char: 'か', romaji: 'ka', row: 'k', type: AlphabetType.HIRAGANA, group: KanaGroup.HIRAGANA_BASIC },
  { char: 'き', romaji: 'ki', row: 'k', type: AlphabetType.HIRAGANA, group: KanaGroup.HIRAGANA_BASIC },
  { char: 'く', romaji: 'ku', row: 'k', type: AlphabetType.HIRAGANA, group: KanaGroup.HIRAGANA_BASIC },
  { char: 'け', romaji: 'ke', row: 'k', type: AlphabetType.HIRAGANA, group: KanaGroup.HIRAGANA_BASIC },
  { char: 'こ', romaji: 'ko', row: 'k', type: AlphabetType.HIRAGANA, group: KanaGroup.HIRAGANA_BASIC },
  { char: 'さ', romaji: 'sa', row: 's', type: AlphabetType.HIRAGANA, group: KanaGroup.HIRAGANA_BASIC },
  { char: 'し', romaji: 'shi', row: 's', type: AlphabetType.HIRAGANA, group: KanaGroup.HIRAGANA_BASIC },
  { char: 'す', romaji: 'su', row: 's', type: AlphabetType.HIRAGANA, group: KanaGroup.HIRAGANA_BASIC },
  { char: 'せ', romaji: 'se', row: 's', type: AlphabetType.HIRAGANA, group: KanaGroup.HIRAGANA_BASIC },
  { char: 'そ', romaji: 'so', row: 's', type: AlphabetType.HIRAGANA, group: KanaGroup.HIRAGANA_BASIC },
  { char: 'た', romaji: 'ta', row: 't', type: AlphabetType.HIRAGANA, group: KanaGroup.HIRAGANA_BASIC },
  { char: 'ち', romaji: 'chi', row: 't', type: AlphabetType.HIRAGANA, group: KanaGroup.HIRAGANA_BASIC },
  { char: 'つ', romaji: 'tsu', row: 't', type: AlphabetType.HIRAGANA, group: KanaGroup.HIRAGANA_BASIC },
  { char: 'て', romaji: 'te', row: 't', type: AlphabetType.HIRAGANA, group: KanaGroup.HIRAGANA_BASIC },
  { char: 'と', romaji: 'to', row: 't', type: AlphabetType.HIRAGANA, group: KanaGroup.HIRAGANA_BASIC },
  { char: 'な', romaji: 'na', row: 'n', type: AlphabetType.HIRAGANA, group: KanaGroup.HIRAGANA_BASIC },
  { char: 'に', romaji: 'ni', row: 'n', type: AlphabetType.HIRAGANA, group: KanaGroup.HIRAGANA_BASIC },
  { char: 'ぬ', romaji: 'nu', row: 'n', type: AlphabetType.HIRAGANA, group: KanaGroup.HIRAGANA_BASIC },
  { char: 'ね', romaji: 'ne', row: 'n', type: AlphabetType.HIRAGANA, group: KanaGroup.HIRAGANA_BASIC },
  { char: 'の', romaji: 'no', row: 'n', type: AlphabetType.HIRAGANA, group: KanaGroup.HIRAGANA_BASIC },
  { char: 'は', romaji: 'ha', row: 'h', type: AlphabetType.HIRAGANA, group: KanaGroup.HIRAGANA_BASIC },
  { char: 'ひ', romaji: 'hi', row: 'h', type: AlphabetType.HIRAGANA, group: KanaGroup.HIRAGANA_BASIC },
  { char: 'ふ', romaji: 'fu', row: 'h', type: AlphabetType.HIRAGANA, group: KanaGroup.HIRAGANA_BASIC },
  { char: 'へ', romaji: 'he', row: 'h', type: AlphabetType.HIRAGANA, group: KanaGroup.HIRAGANA_BASIC },
  { char: 'ほ', romaji: 'ho', row: 'h', type: AlphabetType.HIRAGANA, group: KanaGroup.HIRAGANA_BASIC },
  { char: 'ま', romaji: 'ma', row: 'm', type: AlphabetType.HIRAGANA, group: KanaGroup.HIRAGANA_BASIC },
  { char: 'み', romaji: 'mi', row: 'm', type: AlphabetType.HIRAGANA, group: KanaGroup.HIRAGANA_BASIC },
  { char: 'む', romaji: 'mu', row: 'm', type: AlphabetType.HIRAGANA, group: KanaGroup.HIRAGANA_BASIC },
  { char: 'め', romaji: 'me', row: 'm', type: AlphabetType.HIRAGANA, group: KanaGroup.HIRAGANA_BASIC },
  { char: 'も', romaji: 'mo', row: 'm', type: AlphabetType.HIRAGANA, group: KanaGroup.HIRAGANA_BASIC },
  { char: 'や', romaji: 'ya', row: 'y', type: AlphabetType.HIRAGANA, group: KanaGroup.HIRAGANA_BASIC },
  { char: 'ゆ', romaji: 'yu', row: 'y', type: AlphabetType.HIRAGANA, group: KanaGroup.HIRAGANA_BASIC },
  { char: 'よ', romaji: 'yo', row: 'y', type: AlphabetType.HIRAGANA, group: KanaGroup.HIRAGANA_BASIC },
  { char: 'ら', romaji: 'ra', row: 'r', type: AlphabetType.HIRAGANA, group: KanaGroup.HIRAGANA_BASIC },
  { char: 'り', romaji: 'ri', row: 'r', type: AlphabetType.HIRAGANA, group: KanaGroup.HIRAGANA_BASIC },
  { char: 'る', romaji: 'ru', row: 'r', type: AlphabetType.HIRAGANA, group: KanaGroup.HIRAGANA_BASIC },
  { char: 'れ', romaji: 're', row: 'r', type: AlphabetType.HIRAGANA, group: KanaGroup.HIRAGANA_BASIC },
  { char: 'ろ', romaji: 'ro', row: 'r', type: AlphabetType.HIRAGANA, group: KanaGroup.HIRAGANA_BASIC },
  { char: 'わ', romaji: 'wa', row: 'w', type: AlphabetType.HIRAGANA, group: KanaGroup.HIRAGANA_BASIC },
  { char: 'を', romaji: 'wo', row: 'w', type: AlphabetType.HIRAGANA, group: KanaGroup.HIRAGANA_BASIC },
  { char: 'ん', romaji: 'n', row: 'special', type: AlphabetType.HIRAGANA, group: KanaGroup.HIRAGANA_BASIC },
];

const KATAKANA_BASIC: KanaChar[] = [
  { char: 'ア', romaji: 'a', row: 'vowel', type: AlphabetType.KATAKANA, group: KanaGroup.KATAKANA_BASIC },
  { char: 'イ', romaji: 'i', row: 'vowel', type: AlphabetType.KATAKANA, group: KanaGroup.KATAKANA_BASIC },
  { char: 'ウ', romaji: 'u', row: 'vowel', type: AlphabetType.KATAKANA, group: KanaGroup.KATAKANA_BASIC },
  { char: 'エ', romaji: 'e', row: 'vowel', type: AlphabetType.KATAKANA, group: KanaGroup.KATAKANA_BASIC },
  { char: 'オ', romaji: 'o', row: 'vowel', type: AlphabetType.KATAKANA, group: KanaGroup.KATAKANA_BASIC },
  { char: 'カ', romaji: 'ka', row: 'k', type: AlphabetType.KATAKANA, group: KanaGroup.KATAKANA_BASIC },
  { char: 'キ', romaji: 'ki', row: 'k', type: AlphabetType.KATAKANA, group: KanaGroup.KATAKANA_BASIC },
  { char: 'ク', romaji: 'ku', row: 'k', type: AlphabetType.KATAKANA, group: KanaGroup.KATAKANA_BASIC },
  { char: 'ケ', romaji: 'ke', row: 'k', type: AlphabetType.KATAKANA, group: KanaGroup.KATAKANA_BASIC },
  { char: 'コ', romaji: 'ko', row: 'k', type: AlphabetType.KATAKANA, group: KanaGroup.KATAKANA_BASIC },
  { char: 'サ', romaji: 'sa', row: 's', type: AlphabetType.KATAKANA, group: KanaGroup.KATAKANA_BASIC },
  { char: 'シ', romaji: 'shi', row: 's', type: AlphabetType.KATAKANA, group: KanaGroup.KATAKANA_BASIC },
  { char: 'ス', romaji: 'su', row: 's', type: AlphabetType.KATAKANA, group: KanaGroup.KATAKANA_BASIC },
  { char: 'セ', romaji: 'se', row: 's', type: AlphabetType.KATAKANA, group: KanaGroup.KATAKANA_BASIC },
  { char: 'ソ', romaji: 'so', row: 's', type: AlphabetType.KATAKANA, group: KanaGroup.KATAKANA_BASIC },
  { char: 'タ', romaji: 'ta', row: 't', type: AlphabetType.KATAKANA, group: KanaGroup.KATAKANA_BASIC },
  { char: 'チ', romaji: 'chi', row: 't', type: AlphabetType.KATAKANA, group: KanaGroup.KATAKANA_BASIC },
  { char: 'ツ', romaji: 'tsu', row: 't', type: AlphabetType.KATAKANA, group: KanaGroup.KATAKANA_BASIC },
  { char: 'テ', romaji: 'te', row: 't', type: AlphabetType.KATAKANA, group: KanaGroup.KATAKANA_BASIC },
  { char: 'ト', romaji: 'to', row: 't', type: AlphabetType.KATAKANA, group: KanaGroup.KATAKANA_BASIC },
  { char: 'ナ', romaji: 'na', row: 'n', type: AlphabetType.KATAKANA, group: KanaGroup.KATAKANA_BASIC },
  { char: 'ニ', romaji: 'ni', row: 'n', type: AlphabetType.KATAKANA, group: KanaGroup.KATAKANA_BASIC },
  { char: 'ヌ', romaji: 'nu', row: 'n', type: AlphabetType.KATAKANA, group: KanaGroup.KATAKANA_BASIC },
  { char: 'ネ', romaji: 'ne', row: 'n', type: AlphabetType.KATAKANA, group: KanaGroup.KATAKANA_BASIC },
  { char: 'ノ', romaji: 'no', row: 'n', type: AlphabetType.KATAKANA, group: KanaGroup.KATAKANA_BASIC },
  { char: 'ハ', romaji: 'ha', row: 'h', type: AlphabetType.KATAKANA, group: KanaGroup.KATAKANA_BASIC },
  { char: 'ヒ', romaji: 'hi', row: 'h', type: AlphabetType.KATAKANA, group: KanaGroup.KATAKANA_BASIC },
  { char: 'フ', romaji: 'fu', row: 'h', type: AlphabetType.KATAKANA, group: KanaGroup.KATAKANA_BASIC },
  { char: 'ヘ', romaji: 'he', row: 'h', type: AlphabetType.KATAKANA, group: KanaGroup.KATAKANA_BASIC },
  { char: 'ホ', romaji: 'ho', row: 'h', type: AlphabetType.KATAKANA, group: KanaGroup.KATAKANA_BASIC },
  { char: 'マ', romaji: 'ma', row: 'm', type: AlphabetType.KATAKANA, group: KanaGroup.KATAKANA_BASIC },
  { char: 'ミ', romaji: 'mi', row: 'm', type: AlphabetType.KATAKANA, group: KanaGroup.KATAKANA_BASIC },
  { char: 'ム', romaji: 'mu', row: 'm', type: AlphabetType.KATAKANA, group: KanaGroup.KATAKANA_BASIC },
  { char: 'メ', romaji: 'me', row: 'm', type: AlphabetType.KATAKANA, group: KanaGroup.KATAKANA_BASIC },
  { char: 'モ', romaji: 'mo', row: 'm', type: AlphabetType.KATAKANA, group: KanaGroup.KATAKANA_BASIC },
  { char: 'ヤ', romaji: 'ya', row: 'y', type: AlphabetType.KATAKANA, group: KanaGroup.KATAKANA_BASIC },
  { char: 'ユ', romaji: 'yu', row: 'y', type: AlphabetType.KATAKANA, group: KanaGroup.KATAKANA_BASIC },
  { char: 'ヨ', romaji: 'yo', row: 'y', type: AlphabetType.KATAKANA, group: KanaGroup.KATAKANA_BASIC },
  { char: 'ら', romaji: 'ra', row: 'r', type: AlphabetType.KATAKANA, group: KanaGroup.KATAKANA_BASIC },
  { char: 'リ', romaji: 'ri', row: 'r', type: AlphabetType.KATAKANA, group: KanaGroup.KATAKANA_BASIC },
  { char: 'ル', romaji: 'ru', row: 'r', type: AlphabetType.KATAKANA, group: KanaGroup.KATAKANA_BASIC },
  { char: 'レ', romaji: 're', row: 'r', type: AlphabetType.KATAKANA, group: KanaGroup.KATAKANA_BASIC },
  { char: 'ロ', romaji: 'ro', row: 'r', type: AlphabetType.KATAKANA, group: KanaGroup.KATAKANA_BASIC },
  { char: 'ワ', romaji: 'wa', row: 'w', type: AlphabetType.KATAKANA, group: KanaGroup.KATAKANA_BASIC },
  { char: 'ヲ', romaji: 'wo', row: 'w', type: AlphabetType.KATAKANA, group: KanaGroup.KATAKANA_BASIC },
  { char: 'ン', romaji: 'n', row: 'special', type: AlphabetType.KATAKANA, group: KanaGroup.KATAKANA_BASIC },
];

const HIRAGANA_DAKUTEN: KanaChar[] = [
  { char: 'が', romaji: 'ga', row: 'g', type: AlphabetType.HIRAGANA, group: KanaGroup.HIRAGANA_DAKUTEN },
  { char: 'ぎ', romaji: 'gi', row: 'g', type: AlphabetType.HIRAGANA, group: KanaGroup.HIRAGANA_DAKUTEN },
  { char: 'ぐ', romaji: 'gu', row: 'g', type: AlphabetType.HIRAGANA, group: KanaGroup.HIRAGANA_DAKUTEN },
  { char: 'げ', romaji: 'ge', row: 'g', type: AlphabetType.HIRAGANA, group: KanaGroup.HIRAGANA_DAKUTEN },
  { char: 'ご', romaji: 'go', row: 'g', type: AlphabetType.HIRAGANA, group: KanaGroup.HIRAGANA_DAKUTEN },
  { char: 'ざ', romaji: 'za', row: 'z', type: AlphabetType.HIRAGANA, group: KanaGroup.HIRAGANA_DAKUTEN },
  { char: 'じ', romaji: 'ji', row: 'z', type: AlphabetType.HIRAGANA, group: KanaGroup.HIRAGANA_DAKUTEN },
  { char: 'ず', romaji: 'zu', row: 'z', type: AlphabetType.HIRAGANA, group: KanaGroup.HIRAGANA_DAKUTEN },
  { char: 'ぜ', romaji: 'ze', row: 'z', type: AlphabetType.HIRAGANA, group: KanaGroup.HIRAGANA_DAKUTEN },
  { char: 'ぞ', romaji: 'zo', row: 'z', type: AlphabetType.HIRAGANA, group: KanaGroup.HIRAGANA_DAKUTEN },
  { char: 'だ', romaji: 'da', row: 'd', type: AlphabetType.HIRAGANA, group: KanaGroup.HIRAGANA_DAKUTEN },
  { char: 'ぢ', romaji: 'ji', row: 'd', type: AlphabetType.HIRAGANA, group: KanaGroup.HIRAGANA_DAKUTEN },
  { char: 'づ', romaji: 'zu', row: 'd', type: AlphabetType.HIRAGANA, group: KanaGroup.HIRAGANA_DAKUTEN },
  { char: 'で', romaji: 'de', row: 'd', type: AlphabetType.HIRAGANA, group: KanaGroup.HIRAGANA_DAKUTEN },
  { char: 'ど', romaji: 'do', row: 'd', type: AlphabetType.HIRAGANA, group: KanaGroup.HIRAGANA_DAKUTEN },
  { char: 'ば', romaji: 'ba', row: 'b', type: AlphabetType.HIRAGANA, group: KanaGroup.HIRAGANA_DAKUTEN },
  { char: 'び', romaji: 'bi', row: 'b', type: AlphabetType.HIRAGANA, group: KanaGroup.HIRAGANA_DAKUTEN },
  { char: 'ぶ', romaji: 'bu', row: 'b', type: AlphabetType.HIRAGANA, group: KanaGroup.HIRAGANA_DAKUTEN },
  { char: 'べ', romaji: 'be', row: 'b', type: AlphabetType.HIRAGANA, group: KanaGroup.HIRAGANA_DAKUTEN },
  { char: 'ぼ', romaji: 'bo', row: 'b', type: AlphabetType.HIRAGANA, group: KanaGroup.HIRAGANA_DAKUTEN },
  { char: 'ぱ', romaji: 'pa', row: 'p', type: AlphabetType.HIRAGANA, group: KanaGroup.HIRAGANA_DAKUTEN },
  { char: 'ぴ', romaji: 'pi', row: 'p', type: AlphabetType.HIRAGANA, group: KanaGroup.HIRAGANA_DAKUTEN },
  { char: 'ぷ', romaji: 'pu', row: 'p', type: AlphabetType.HIRAGANA, group: KanaGroup.HIRAGANA_DAKUTEN },
  { char: 'ぺ', romaji: 'pe', row: 'p', type: AlphabetType.HIRAGANA, group: KanaGroup.HIRAGANA_DAKUTEN },
  { char: 'ぽ', romaji: 'po', row: 'p', type: AlphabetType.HIRAGANA, group: KanaGroup.HIRAGANA_DAKUTEN },
];

const KATAKANA_DAKUTEN: KanaChar[] = [
  { char: 'ガ', romaji: 'ga', row: 'g', type: AlphabetType.KATAKANA, group: KanaGroup.KATAKANA_DAKUTEN },
  { char: 'ギ', romaji: 'gi', row: 'g', type: AlphabetType.KATAKANA, group: KanaGroup.KATAKANA_DAKUTEN },
  { char: 'グ', romaji: 'gu', row: 'g', type: AlphabetType.KATAKANA, group: KanaGroup.KATAKANA_DAKUTEN },
  { char: 'ゲ', romaji: 'ge', row: 'g', type: AlphabetType.KATAKANA, group: KanaGroup.KATAKANA_DAKUTEN },
  { char: 'ゴ', romaji: 'go', row: 'g', type: AlphabetType.KATAKANA, group: KanaGroup.KATAKANA_DAKUTEN },
  { char: 'ザ', romaji: 'za', row: 'z', type: AlphabetType.KATAKANA, group: KanaGroup.KATAKANA_DAKUTEN },
  { char: 'ジ', romaji: 'ji', row: 'z', type: AlphabetType.KATAKANA, group: KanaGroup.KATAKANA_DAKUTEN },
  { char: 'ズ', romaji: 'zu', row: 'z', type: AlphabetType.KATAKANA, group: KanaGroup.KATAKANA_DAKUTEN },
  { char: 'ゼ', romaji: 'ze', row: 'z', type: AlphabetType.KATAKANA, group: KanaGroup.KATAKANA_DAKUTEN },
  { char: 'ゾ', romaji: 'zo', row: 'z', type: AlphabetType.KATAKANA, group: KanaGroup.KATAKANA_DAKUTEN },
  { char: 'ダ', romaji: 'da', row: 'd', type: AlphabetType.KATAKANA, group: KanaGroup.KATAKANA_DAKUTEN },
  { char: 'ヂ', romaji: 'ji', row: 'd', type: AlphabetType.KATAKANA, group: KanaGroup.KATAKANA_DAKUTEN },
  { char: 'ヅ', romaji: 'zu', row: 'd', type: AlphabetType.KATAKANA, group: KanaGroup.KATAKANA_DAKUTEN },
  { char: 'デ', romaji: 'de', row: 'd', type: AlphabetType.KATAKANA, group: KanaGroup.KATAKANA_DAKUTEN },
  { char: 'ド', romaji: 'do', row: 'd', type: AlphabetType.KATAKANA, group: KanaGroup.KATAKANA_DAKUTEN },
  { char: 'バ', romaji: 'ba', row: 'b', type: AlphabetType.KATAKANA, group: KanaGroup.KATAKANA_DAKUTEN },
  { char: 'ビ', romaji: 'bi', row: 'b', type: AlphabetType.KATAKANA, group: KanaGroup.KATAKANA_DAKUTEN },
  { char: 'ブ', romaji: 'bu', row: 'b', type: AlphabetType.KATAKANA, group: KanaGroup.KATAKANA_DAKUTEN },
  { char: 'ベ', romaji: 'be', row: 'b', type: AlphabetType.KATAKANA, group: KanaGroup.KATAKANA_DAKUTEN },
  { char: 'ボ', romaji: 'bo', row: 'b', type: AlphabetType.KATAKANA, group: KanaGroup.KATAKANA_DAKUTEN },
  { char: 'パ', romaji: 'pa', row: 'p', type: AlphabetType.KATAKANA, group: KanaGroup.KATAKANA_DAKUTEN },
  { char: 'ピ', romaji: 'pi', row: 'p', type: AlphabetType.KATAKANA, group: KanaGroup.KATAKANA_DAKUTEN },
  { char: 'プ', romaji: 'pu', row: 'p', type: AlphabetType.KATAKANA, group: KanaGroup.KATAKANA_DAKUTEN },
  { char: 'ペ', romaji: 'pe', row: 'p', type: AlphabetType.KATAKANA, group: KanaGroup.KATAKANA_DAKUTEN },
  { char: 'ポ', romaji: 'po', row: 'p', type: AlphabetType.KATAKANA, group: KanaGroup.KATAKANA_DAKUTEN },
];

const HIRAGANA_YOON: KanaChar[] = [
  { char: 'きゃ', romaji: 'kya', row: 'yoon', type: AlphabetType.HIRAGANA, group: KanaGroup.HIRAGANA_YOON },
  { char: 'きゅ', romaji: 'kyu', row: 'yoon', type: AlphabetType.HIRAGANA, group: KanaGroup.HIRAGANA_YOON },
  { char: 'きょ', romaji: 'kyo', row: 'yoon', type: AlphabetType.HIRAGANA, group: KanaGroup.HIRAGANA_YOON },
  { char: 'しゃ', romaji: 'sha', row: 'yoon', type: AlphabetType.HIRAGANA, group: KanaGroup.HIRAGANA_YOON },
  { char: 'しゅ', romaji: 'shu', row: 'yoon', type: AlphabetType.HIRAGANA, group: KanaGroup.HIRAGANA_YOON },
  { char: 'しょ', romaji: 'sho', row: 'yoon', type: AlphabetType.HIRAGANA, group: KanaGroup.HIRAGANA_YOON },
  { char: 'ちゃ', romaji: 'cha', row: 'yoon', type: AlphabetType.HIRAGANA, group: KanaGroup.HIRAGANA_YOON },
  { char: 'ちゅ', romaji: 'chu', row: 'yoon', type: AlphabetType.HIRAGANA, group: KanaGroup.HIRAGANA_YOON },
  { char: 'ちょ', romaji: 'cho', row: 'yoon', type: AlphabetType.HIRAGANA, group: KanaGroup.HIRAGANA_YOON },
  { char: 'にゃ', romaji: 'nya', row: 'yoon', type: AlphabetType.HIRAGANA, group: KanaGroup.HIRAGANA_YOON },
  { char: 'にゅ', romaji: 'nyu', row: 'yoon', type: AlphabetType.HIRAGANA, group: KanaGroup.HIRAGANA_YOON },
  { char: 'にょ', romaji: 'nyo', row: 'yoon', type: AlphabetType.HIRAGANA, group: KanaGroup.HIRAGANA_YOON },
  { char: 'ひゃ', romaji: 'hya', row: 'yoon', type: AlphabetType.HIRAGANA, group: KanaGroup.HIRAGANA_YOON },
  { char: 'ひゅ', romaji: 'hyu', row: 'yoon', type: AlphabetType.HIRAGANA, group: KanaGroup.HIRAGANA_YOON },
  { char: 'ひょ', romaji: 'hyo', row: 'yoon', type: AlphabetType.HIRAGANA, group: KanaGroup.HIRAGANA_YOON },
  { char: 'みゃ', romaji: 'mya', row: 'yoon', type: AlphabetType.HIRAGANA, group: KanaGroup.HIRAGANA_YOON },
  { char: 'みゅ', romaji: 'myu', row: 'yoon', type: AlphabetType.HIRAGANA, group: KanaGroup.HIRAGANA_YOON },
  { char: 'みょ', romaji: 'myo', row: 'yoon', type: AlphabetType.HIRAGANA, group: KanaGroup.HIRAGANA_YOON },
  { char: 'りゃ', romaji: 'rya', row: 'yoon', type: AlphabetType.HIRAGANA, group: KanaGroup.HIRAGANA_YOON },
  { char: 'りゅ', romaji: 'ryu', row: 'yoon', type: AlphabetType.HIRAGANA, group: KanaGroup.HIRAGANA_YOON },
  { char: 'りょ', romaji: 'ryo', row: 'yoon', type: AlphabetType.HIRAGANA, group: KanaGroup.HIRAGANA_YOON },
  { char: 'ぎゃ', romaji: 'gya', row: 'yoon', type: AlphabetType.HIRAGANA, group: KanaGroup.HIRAGANA_YOON },
  { char: 'ぎゅ', romaji: 'gyu', row: 'yoon', type: AlphabetType.HIRAGANA, group: KanaGroup.HIRAGANA_YOON },
  { char: 'ぎょ', romaji: 'gyo', row: 'yoon', type: AlphabetType.HIRAGANA, group: KanaGroup.HIRAGANA_YOON },
  { char: 'じゃ', romaji: 'ja', row: 'yoon', type: AlphabetType.HIRAGANA, group: KanaGroup.HIRAGANA_YOON },
  { char: 'じゅ', romaji: 'ju', row: 'yoon', type: AlphabetType.HIRAGANA, group: KanaGroup.HIRAGANA_YOON },
  { char: 'じょ', romaji: 'jo', row: 'yoon', type: AlphabetType.HIRAGANA, group: KanaGroup.HIRAGANA_YOON },
  { char: 'びゃ', romaji: 'bya', row: 'yoon', type: AlphabetType.HIRAGANA, group: KanaGroup.HIRAGANA_YOON },
  { char: 'びゅ', romaji: 'byu', row: 'yoon', type: AlphabetType.HIRAGANA, group: KanaGroup.HIRAGANA_YOON },
  { char: 'びょ', romaji: 'byo', row: 'yoon', type: AlphabetType.HIRAGANA, group: KanaGroup.HIRAGANA_YOON },
  { char: 'ぴゃ', romaji: 'pya', row: 'yoon', type: AlphabetType.HIRAGANA, group: KanaGroup.HIRAGANA_YOON },
  { char: 'ぴゅ', romaji: 'pyu', row: 'yoon', type: AlphabetType.HIRAGANA, group: KanaGroup.HIRAGANA_YOON },
  { char: 'ぴょ', romaji: 'pyo', row: 'yoon', type: AlphabetType.HIRAGANA, group: KanaGroup.HIRAGANA_YOON },
];

const SPECIAL_SOUNDS: KanaChar[] = [
  { char: 'きって', romaji: 'kitte', meaning: 'Tem thư (Âm ngắt)', row: 'special', type: AlphabetType.HIRAGANA, group: KanaGroup.SPECIAL_SOUNDS },
  { char: 'ざっし', romaji: 'zasshi', meaning: 'Tạp chí (Âm ngắt)', row: 'special', type: AlphabetType.HIRAGANA, group: KanaGroup.SPECIAL_SOUNDS },
  { char: 'がっこう', romaji: 'gakkou', meaning: 'Trường học (Âm ngắt)', row: 'special', type: AlphabetType.HIRAGANA, group: KanaGroup.SPECIAL_SOUNDS },
  { char: 'おばあさん', romaji: 'obaasan', meaning: 'Bà (Trường âm A)', row: 'special', type: AlphabetType.HIRAGANA, group: KanaGroup.SPECIAL_SOUNDS },
  { char: 'おじいさん', romaji: 'ojiisan', meaning: 'Ông (Trường âm I)', row: 'special', type: AlphabetType.HIRAGANA, group: KanaGroup.SPECIAL_SOUNDS },
  { char: 'すうがく', romaji: 'suugaku', meaning: 'Toán học (Trường âm U)', row: 'special', type: AlphabetType.HIRAGANA, group: KanaGroup.SPECIAL_SOUNDS },
  { char: 'せんせい', romaji: 'sensei', meaning: 'Giáo viên (Trường âm E)', row: 'special', type: AlphabetType.HIRAGANA, group: KanaGroup.SPECIAL_SOUNDS },
  { char: 'おとうさん', romaji: 'otousan', meaning: 'Bố (Trường âm O)', row: 'special', type: AlphabetType.HIRAGANA, group: KanaGroup.SPECIAL_SOUNDS },
];

const NUMBERS: KanaChar[] = [
  { char: '零', romaji: 'rei / zero', meaning: 'Số 0', row: 'num', type: AlphabetType.VOCABULARY, group: KanaGroup.NUMBERS },
  { char: '一', romaji: 'ichi', meaning: 'Số 1', row: 'num', type: AlphabetType.VOCABULARY, group: KanaGroup.NUMBERS },
  { char: '二', romaji: 'ni', meaning: 'Số 2', row: 'num', type: AlphabetType.VOCABULARY, group: KanaGroup.NUMBERS },
  { char: '三', romaji: 'san', meaning: 'Số 3', row: 'num', type: AlphabetType.VOCABULARY, group: KanaGroup.NUMBERS },
  { char: '四', romaji: 'yon / shi', meaning: 'Số 4', row: 'num', type: AlphabetType.VOCABULARY, group: KanaGroup.NUMBERS },
  { char: '五', romaji: 'go', meaning: 'Số 5', row: 'num', type: AlphabetType.VOCABULARY, group: KanaGroup.NUMBERS },
  { char: '六', romaji: 'roku', meaning: 'Số 6', row: 'num', type: AlphabetType.VOCABULARY, group: KanaGroup.NUMBERS },
  { char: '七', romaji: 'nana / shichi', meaning: 'Số 7', row: 'num', type: AlphabetType.VOCABULARY, group: KanaGroup.NUMBERS },
  { char: '八', romaji: 'hachi', meaning: 'Số 8', row: 'num', type: AlphabetType.VOCABULARY, group: KanaGroup.NUMBERS },
  { char: '九', romaji: 'kyuu', meaning: 'Số 9', row: 'num', type: AlphabetType.VOCABULARY, group: KanaGroup.NUMBERS },
  { char: '十', romaji: 'juu', meaning: 'Số 10', row: 'num', type: AlphabetType.VOCABULARY, group: KanaGroup.NUMBERS },
  { char: '十一', romaji: 'juu ichi', meaning: 'Số 11', row: 'num', type: AlphabetType.VOCABULARY, group: KanaGroup.NUMBERS },
  { char: '十二', romaji: 'juu ni', meaning: 'Số 12', row: 'num', type: AlphabetType.VOCABULARY, group: KanaGroup.NUMBERS },
  { char: '二十', romaji: 'ni juu', meaning: 'Số 20', row: 'num', type: AlphabetType.VOCABULARY, group: KanaGroup.NUMBERS },
  { char: '百', romaji: 'hyaku', meaning: '100', row: 'num', type: AlphabetType.VOCABULARY, group: KanaGroup.NUMBERS },
  { char: '千', romaji: 'sen', meaning: '1.000 (Nghìn)', row: 'num', type: AlphabetType.VOCABULARY, group: KanaGroup.NUMBERS },
  { char: '万', romaji: 'man', meaning: '10.000 (Vạn)', row: 'num', type: AlphabetType.VOCABULARY, group: KanaGroup.NUMBERS },
];

const DATES: KanaChar[] = [
  // Days of week
  { char: '月曜日', romaji: 'getsuyoubi', meaning: 'Thứ Hai', row: 'date', type: AlphabetType.VOCABULARY, group: KanaGroup.DATES },
  { char: '火曜日', romaji: 'kayoubi', meaning: 'Thứ Ba', row: 'date', type: AlphabetType.VOCABULARY, group: KanaGroup.DATES },
  { char: '水曜日', romaji: 'suiyoubi', meaning: 'Thứ Tư', row: 'date', type: AlphabetType.VOCABULARY, group: KanaGroup.DATES },
  { char: '木曜日', romaji: 'mokuyoubi', meaning: 'Thứ Năm', row: 'date', type: AlphabetType.VOCABULARY, group: KanaGroup.DATES },
  { char: '金曜日', romaji: 'kinyoubi', meaning: 'Thứ Sáu', row: 'date', type: AlphabetType.VOCABULARY, group: KanaGroup.DATES },
  { char: '土曜日', romaji: 'doyoubi', meaning: 'Thứ Bảy', row: 'date', type: AlphabetType.VOCABULARY, group: KanaGroup.DATES },
  { char: '日曜日', romaji: 'nichiyoubi', meaning: 'Chủ Nhật', row: 'date', type: AlphabetType.VOCABULARY, group: KanaGroup.DATES },
  // Months
  { char: '一月', romaji: 'ichigatsu', meaning: 'Tháng 1', row: 'date', type: AlphabetType.VOCABULARY, group: KanaGroup.DATES },
  { char: '二月', romaji: 'nigatsu', meaning: 'Tháng 2', row: 'date', type: AlphabetType.VOCABULARY, group: KanaGroup.DATES },
  { char: '三月', romaji: 'sangatsu', meaning: 'Tháng 3', row: 'date', type: AlphabetType.VOCABULARY, group: KanaGroup.DATES },
  { char: '四月', romaji: 'shigatsu', meaning: 'Tháng 4', row: 'date', type: AlphabetType.VOCABULARY, group: KanaGroup.DATES },
  { char: '五月', romaji: 'gogatsu', meaning: 'Tháng 5', row: 'date', type: AlphabetType.VOCABULARY, group: KanaGroup.DATES },
  { char: '六月', romaji: 'rokugatsu', meaning: 'Tháng 6', row: 'date', type: AlphabetType.VOCABULARY, group: KanaGroup.DATES },
  { char: '十二月', romaji: 'juunigatsu', meaning: 'Tháng 12', row: 'date', type: AlphabetType.VOCABULARY, group: KanaGroup.DATES },
];

const N5_PRONOUNS: KanaChar[] = [
  { char: 'わたし', romaji: 'watashi', meaning: 'Tôi', row: 'pronoun', type: AlphabetType.VOCABULARY, group: KanaGroup.N5_PRONOUNS },
  { char: 'あなた', romaji: 'anata', meaning: 'Bạn', row: 'pronoun', type: AlphabetType.VOCABULARY, group: KanaGroup.N5_PRONOUNS },
  { char: 'かれ', romaji: 'kare', meaning: 'Anh ấy', row: 'pronoun', type: AlphabetType.VOCABULARY, group: KanaGroup.N5_PRONOUNS },
  { char: 'かのじょ', romaji: 'kanojo', meaning: 'Cô ấy', row: 'pronoun', type: AlphabetType.VOCABULARY, group: KanaGroup.N5_PRONOUNS },
  { char: 'これ', romaji: 'kore', meaning: 'Cái này (gần người nói)', row: 'kosoado', type: AlphabetType.VOCABULARY, group: KanaGroup.N5_PRONOUNS },
  { char: 'それ', romaji: 'sore', meaning: 'Cái đó (gần người nghe)', row: 'kosoado', type: AlphabetType.VOCABULARY, group: KanaGroup.N5_PRONOUNS },
  { char: 'あれ', romaji: 'are', meaning: 'Cái kia (xa cả hai)', row: 'kosoado', type: AlphabetType.VOCABULARY, group: KanaGroup.N5_PRONOUNS },
  { char: 'どれ', romaji: 'dore', meaning: 'Cái nào?', row: 'kosoado', type: AlphabetType.VOCABULARY, group: KanaGroup.N5_PRONOUNS },
  { char: 'ここ', romaji: 'koko', meaning: 'Chỗ này', row: 'kosoado', type: AlphabetType.VOCABULARY, group: KanaGroup.N5_PRONOUNS },
  { char: 'そこ', romaji: 'soko', meaning: 'Chỗ đó', row: 'kosoado', type: AlphabetType.VOCABULARY, group: KanaGroup.N5_PRONOUNS },
  { char: 'あそこ', romaji: 'asoko', meaning: 'Chỗ kia', row: 'kosoado', type: AlphabetType.VOCABULARY, group: KanaGroup.N5_PRONOUNS },
  { char: 'どこ', romaji: 'doko', meaning: 'Ở đâu?', row: 'kosoado', type: AlphabetType.VOCABULARY, group: KanaGroup.N5_PRONOUNS },
];

const N5_ADJECTIVES: KanaChar[] = [
  { char: 'たかい', romaji: 'takai', meaning: 'Cao / Đắt', row: 'adj-i', type: AlphabetType.VOCABULARY, group: KanaGroup.N5_ADJECTIVES },
  { char: 'ひくい', romaji: 'hikui', meaning: 'Thấp', row: 'adj-i', type: AlphabetType.VOCABULARY, group: KanaGroup.N5_ADJECTIVES },
  { char: 'やすい', romaji: 'yasui', meaning: 'Rẻ', row: 'adj-i', type: AlphabetType.VOCABULARY, group: KanaGroup.N5_ADJECTIVES },
  { char: 'おいしい', romaji: 'oishii', meaning: 'Ngon', row: 'adj-i', type: AlphabetType.VOCABULARY, group: KanaGroup.N5_ADJECTIVES },
  { char: 'おおきい', romaji: 'ookii', meaning: 'To, lớn', row: 'adj-i', type: AlphabetType.VOCABULARY, group: KanaGroup.N5_ADJECTIVES },
  { char: 'ちいさい', romaji: 'chiisai', meaning: 'Nhỏ, bé', row: 'adj-i', type: AlphabetType.VOCABULARY, group: KanaGroup.N5_ADJECTIVES },
  { char: 'あつい', romaji: 'atsui', meaning: 'Nóng', row: 'adj-i', type: AlphabetType.VOCABULARY, group: KanaGroup.N5_ADJECTIVES },
  { char: 'さむい', romaji: 'samui', meaning: 'Lạnh (thời tiết)', row: 'adj-i', type: AlphabetType.VOCABULARY, group: KanaGroup.N5_ADJECTIVES },
  { char: 'きれい', romaji: 'kirei (na)', meaning: 'Đẹp / Sạch', row: 'adj-na', type: AlphabetType.VOCABULARY, group: KanaGroup.N5_ADJECTIVES },
  { char: 'しずか', romaji: 'shizuka (na)', meaning: 'Yên tĩnh', row: 'adj-na', type: AlphabetType.VOCABULARY, group: KanaGroup.N5_ADJECTIVES },
  { char: 'べんり', romaji: 'benri (na)', meaning: 'Tiện lợi', row: 'adj-na', type: AlphabetType.VOCABULARY, group: KanaGroup.N5_ADJECTIVES },
  { char: 'ゆうめい', romaji: 'yuumei (na)', meaning: 'Nổi tiếng', row: 'adj-na', type: AlphabetType.VOCABULARY, group: KanaGroup.N5_ADJECTIVES },
  { char: 'げんき', romaji: 'genki (na)', meaning: 'Khỏe mạnh', row: 'adj-na', type: AlphabetType.VOCABULARY, group: KanaGroup.N5_ADJECTIVES },
  // Expanded
  { char: 'あたらしい', romaji: 'atarashii', meaning: 'Mới', row: 'adj-i', type: AlphabetType.VOCABULARY, group: KanaGroup.N5_ADJECTIVES },
  { char: 'ふるい', romaji: 'furui', meaning: 'Cũ', row: 'adj-i', type: AlphabetType.VOCABULARY, group: KanaGroup.N5_ADJECTIVES },
  { char: 'いい / よい', romaji: 'ii / yoi', meaning: 'Tốt', row: 'adj-i', type: AlphabetType.VOCABULARY, group: KanaGroup.N5_ADJECTIVES },
  { char: 'わるい', romaji: 'warui', meaning: 'Xấu', row: 'adj-i', type: AlphabetType.VOCABULARY, group: KanaGroup.N5_ADJECTIVES },
  { char: 'いそがしい', romaji: 'isogashii', meaning: 'Bận rộn', row: 'adj-i', type: AlphabetType.VOCABULARY, group: KanaGroup.N5_ADJECTIVES },
  { char: 'たのしい', romaji: 'tanoshii', meaning: 'Vui vẻ', row: 'adj-i', type: AlphabetType.VOCABULARY, group: KanaGroup.N5_ADJECTIVES },
  { char: 'おもしろい', romaji: 'omoshiroi', meaning: 'Thú vị', row: 'adj-i', type: AlphabetType.VOCABULARY, group: KanaGroup.N5_ADJECTIVES },
  { char: 'つまらない', romaji: 'tsumaranai', meaning: 'Nhàm chán', row: 'adj-i', type: AlphabetType.VOCABULARY, group: KanaGroup.N5_ADJECTIVES },
  { char: 'すき', romaji: 'suki (na)', meaning: 'Thích', row: 'adj-na', type: AlphabetType.VOCABULARY, group: KanaGroup.N5_ADJECTIVES },
  { char: 'きらい', romaji: 'kirai (na)', meaning: 'Ghét', row: 'adj-na', type: AlphabetType.VOCABULARY, group: KanaGroup.N5_ADJECTIVES },
  { char: 'じょうず', romaji: 'jouzu (na)', meaning: 'Giỏi', row: 'adj-na', type: AlphabetType.VOCABULARY, group: KanaGroup.N5_ADJECTIVES },
  { char: 'へた', romaji: 'heta (na)', meaning: 'Kém', row: 'adj-na', type: AlphabetType.VOCABULARY, group: KanaGroup.N5_ADJECTIVES },
];

const N5_VERBS: KanaChar[] = [
  { char: 'たべます', romaji: 'tabemasu', meaning: 'Ăn', row: 'verb', type: AlphabetType.VOCABULARY, group: KanaGroup.N5_VERBS },
  { char: 'のみます', romaji: 'nomimasu', meaning: 'Uống', row: 'verb', type: AlphabetType.VOCABULARY, group: KanaGroup.N5_VERBS },
  { char: 'いきます', romaji: 'ikimasu', meaning: 'Đi', row: 'verb', type: AlphabetType.VOCABULARY, group: KanaGroup.N5_VERBS },
  { char: 'きます', romaji: 'kimasu', meaning: 'Đến', row: 'verb', type: AlphabetType.VOCABULARY, group: KanaGroup.N5_VERBS },
  { char: 'かえります', romaji: 'kaerimasu', meaning: 'Về', row: 'verb', type: AlphabetType.VOCABULARY, group: KanaGroup.N5_VERBS },
  { char: 'みます', romaji: 'mimasu', meaning: 'Xem, nhìn', row: 'verb', type: AlphabetType.VOCABULARY, group: KanaGroup.N5_VERBS },
  { char: 'ききます', romaji: 'kikimasu', meaning: 'Nghe', row: 'verb', type: AlphabetType.VOCABULARY, group: KanaGroup.N5_VERBS },
  { char: 'よみます', romaji: 'yomimasu', meaning: 'Đọc', row: 'verb', type: AlphabetType.VOCABULARY, group: KanaGroup.N5_VERBS },
  { char: 'かきます', romaji: 'kakimasu', meaning: 'Viết', row: 'verb', type: AlphabetType.VOCABULARY, group: KanaGroup.N5_VERBS },
  { char: 'かいます', romaji: 'kaimasu', meaning: 'Mua', row: 'verb', type: AlphabetType.VOCABULARY, group: KanaGroup.N5_VERBS },
  { char: 'します', romaji: 'shimasu', meaning: 'Làm', row: 'verb', type: AlphabetType.VOCABULARY, group: KanaGroup.N5_VERBS },
  { char: 'ねます', romaji: 'nemasu', meaning: 'Ngủ', row: 'verb', type: AlphabetType.VOCABULARY, group: KanaGroup.N5_VERBS },
  // Expanded
  { char: 'おきます', romaji: 'okimasu', meaning: 'Thức dậy', row: 'verb', type: AlphabetType.VOCABULARY, group: KanaGroup.N5_VERBS },
  { char: 'あいます', romaji: 'aimasu', meaning: 'Gặp gỡ', row: 'verb', type: AlphabetType.VOCABULARY, group: KanaGroup.N5_VERBS },
  { char: 'はなします', romaji: 'hanashimasu', meaning: 'Nói chuyện', row: 'verb', type: AlphabetType.VOCABULARY, group: KanaGroup.N5_VERBS },
  { char: 'わかります', romaji: 'wakarimasu', meaning: 'Hiểu', row: 'verb', type: AlphabetType.VOCABULARY, group: KanaGroup.N5_VERBS },
  { char: 'あります', romaji: 'arimasu', meaning: 'Có (vật)', row: 'verb', type: AlphabetType.VOCABULARY, group: KanaGroup.N5_VERBS },
  { char: 'います', romaji: 'imasu', meaning: 'Có (người/con vật)', row: 'verb', type: AlphabetType.VOCABULARY, group: KanaGroup.N5_VERBS },
  { char: 'あそびます', romaji: 'asobimasu', meaning: 'Chơi', row: 'verb', type: AlphabetType.VOCABULARY, group: KanaGroup.N5_VERBS },
  { char: 'べんきょうします', romaji: 'benkyou shimasu', meaning: 'Học', row: 'verb', type: AlphabetType.VOCABULARY, group: KanaGroup.N5_VERBS },
];

const N5_KANJI_BASIC: KanaChar[] = [
  { char: '日', romaji: 'ni / nichi / bi / hi', meaning: 'Mặt trời / Ngày', row: 'kanji', type: AlphabetType.KANJI, group: KanaGroup.N5_KANJI_BASIC },
  { char: '月', romaji: 'gatsu / getsu / tsuki', meaning: 'Mặt trăng / Tháng', row: 'kanji', type: AlphabetType.KANJI, group: KanaGroup.N5_KANJI_BASIC },
  { char: '木', romaji: 'moku / ki', meaning: 'Cây / Gỗ', row: 'kanji', type: AlphabetType.KANJI, group: KanaGroup.N5_KANJI_BASIC },
  { char: '山', romaji: 'san / yama', meaning: 'Núi', row: 'kanji', type: AlphabetType.KANJI, group: KanaGroup.N5_KANJI_BASIC },
  { char: '川', romaji: 'sen / kawa', meaning: 'Sông', row: 'kanji', type: AlphabetType.KANJI, group: KanaGroup.N5_KANJI_BASIC },
  { char: '田', romaji: 'den / ta', meaning: 'Ruộng lúa', row: 'kanji', type: AlphabetType.KANJI, group: KanaGroup.N5_KANJI_BASIC },
  { char: '人', romaji: 'jin / nin / hito', meaning: 'Người', row: 'kanji', type: AlphabetType.KANJI, group: KanaGroup.N5_KANJI_BASIC },
  { char: '口', romaji: 'kou / kuchi', meaning: 'Miệng', row: 'kanji', type: AlphabetType.KANJI, group: KanaGroup.N5_KANJI_BASIC },
  { char: '車', romaji: 'sha / kuruma', meaning: 'Xe ô tô', row: 'kanji', type: AlphabetType.KANJI, group: KanaGroup.N5_KANJI_BASIC },
  { char: '門', romaji: 'mon / kado', meaning: 'Cổng', row: 'kanji', type: AlphabetType.KANJI, group: KanaGroup.N5_KANJI_BASIC },
  { char: '一', romaji: 'ichi / hito', meaning: 'Một', row: 'kanji', type: AlphabetType.KANJI, group: KanaGroup.N5_KANJI_BASIC },
  { char: '二', romaji: 'ni / futa', meaning: 'Hai', row: 'kanji', type: AlphabetType.KANJI, group: KanaGroup.N5_KANJI_BASIC },
  { char: '三', romaji: 'san / mi', meaning: 'Ba', row: 'kanji', type: AlphabetType.KANJI, group: KanaGroup.N5_KANJI_BASIC },
  { char: '十', romaji: 'juu / to', meaning: 'Mười', row: 'kanji', type: AlphabetType.KANJI, group: KanaGroup.N5_KANJI_BASIC },
  { char: '百', romaji: 'hyaku', meaning: 'Trăm', row: 'kanji', type: AlphabetType.KANJI, group: KanaGroup.N5_KANJI_BASIC },
  { char: '千', romaji: 'sen / chi', meaning: 'Nghìn', row: 'kanji', type: AlphabetType.KANJI, group: KanaGroup.N5_KANJI_BASIC },
  { char: '大', romaji: 'dai / oo', meaning: 'To lớn', row: 'kanji', type: AlphabetType.KANJI, group: KanaGroup.N5_KANJI_BASIC },
  { char: '小', romaji: 'shou / chii', meaning: 'Nhỏ bé', row: 'kanji', type: AlphabetType.KANJI, group: KanaGroup.N5_KANJI_BASIC },
  { char: '中', romaji: 'chuu / naka', meaning: 'Ở trong / Trung tâm', row: 'kanji', type: AlphabetType.KANJI, group: KanaGroup.N5_KANJI_BASIC },
  { char: '国', romaji: 'koku / kuni', meaning: 'Đất nước', row: 'kanji', type: AlphabetType.KANJI, group: KanaGroup.N5_KANJI_BASIC },
];

const N5_PARTICLES: KanaChar[] = [
  { char: 'は', romaji: 'wa', meaning: 'Trợ từ chủ ngữ (đọc là WA)', row: 'particle', type: AlphabetType.GRAMMAR, group: KanaGroup.N5_PARTICLES },
  { char: 'が', romaji: 'ga', meaning: 'Trợ từ chủ ngữ (nhấn mạnh)', row: 'particle', type: AlphabetType.GRAMMAR, group: KanaGroup.N5_PARTICLES },
  { char: 'を', romaji: 'o', meaning: 'Trợ từ tân ngữ (đọc là O)', row: 'particle', type: AlphabetType.GRAMMAR, group: KanaGroup.N5_PARTICLES },
  { char: 'に', romaji: 'ni', meaning: 'Trợ từ chỉ địa điểm/thời gian', row: 'particle', type: AlphabetType.GRAMMAR, group: KanaGroup.N5_PARTICLES },
  { char: 'で', romaji: 'de', meaning: 'Trợ từ chỉ nơi chốn/phương tiện', row: 'particle', type: AlphabetType.GRAMMAR, group: KanaGroup.N5_PARTICLES },
  { char: 'へ', romaji: 'e', meaning: 'Trợ từ chỉ phương hướng (đọc là E)', row: 'particle', type: AlphabetType.GRAMMAR, group: KanaGroup.N5_PARTICLES },
  { char: 'と', romaji: 'to', meaning: 'Và / Với', row: 'particle', type: AlphabetType.GRAMMAR, group: KanaGroup.N5_PARTICLES },
  { char: 'の', romaji: 'no', meaning: 'Của (sở hữu)', row: 'particle', type: AlphabetType.GRAMMAR, group: KanaGroup.N5_PARTICLES },
  { char: 'ですか', romaji: 'desu ka', meaning: 'Câu hỏi (Là ... phải không?)', row: 'grammar', type: AlphabetType.GRAMMAR, group: KanaGroup.N5_PARTICLES },
  { char: 'なん / なに', romaji: 'nan / nani', meaning: 'Cái gì?', row: 'question', type: AlphabetType.GRAMMAR, group: KanaGroup.N5_PARTICLES },
  { char: 'だれ', romaji: 'dare', meaning: 'Ai?', row: 'question', type: AlphabetType.GRAMMAR, group: KanaGroup.N5_PARTICLES },
  { char: 'いつ', romaji: 'itsu', meaning: 'Khi nào?', row: 'question', type: AlphabetType.GRAMMAR, group: KanaGroup.N5_PARTICLES },
  { char: 'どうして', romaji: 'doushite', meaning: 'Tại sao?', row: 'question', type: AlphabetType.GRAMMAR, group: KanaGroup.N5_PARTICLES },
];

const N5_GREETINGS: KanaChar[] = [
  { char: 'おはよう', romaji: 'ohayou', meaning: 'Chào buổi sáng (thân mật)', row: 'phrase', type: AlphabetType.PHRASE, group: KanaGroup.N5_GREETINGS },
  { char: 'こんにちは', romaji: 'konnichiwa', meaning: 'Xin chào (buổi trưa/chiều)', row: 'phrase', type: AlphabetType.PHRASE, group: KanaGroup.N5_GREETINGS },
  { char: 'こんばんは', romaji: 'konbanwa', meaning: 'Chào buổi tối', row: 'phrase', type: AlphabetType.PHRASE, group: KanaGroup.N5_GREETINGS },
  { char: 'さようなら', romaji: 'sayounara', meaning: 'Tạm biệt (lâu ngày)', row: 'phrase', type: AlphabetType.PHRASE, group: KanaGroup.N5_GREETINGS },
  { char: 'ありがとう', romaji: 'arigatou', meaning: 'Cảm ơn', row: 'phrase', type: AlphabetType.PHRASE, group: KanaGroup.N5_GREETINGS },
  { char: 'すみません', romaji: 'sumimasen', meaning: 'Xin lỗi / Làm ơn', row: 'phrase', type: AlphabetType.PHRASE, group: KanaGroup.N5_GREETINGS },
  { char: 'おやすみなさい', romaji: 'oyasuminasai', meaning: 'Chúc ngủ ngon', row: 'phrase', type: AlphabetType.PHRASE, group: KanaGroup.N5_GREETINGS },
  { char: 'いただきます', romaji: 'itadakimasu', meaning: 'Mời dùng bữa (trước khi ăn)', row: 'phrase', type: AlphabetType.PHRASE, group: KanaGroup.N5_GREETINGS },
  { char: 'ごちそうさま', romaji: 'gochisousama', meaning: 'Cảm ơn vì bữa ăn (sau khi ăn)', row: 'phrase', type: AlphabetType.PHRASE, group: KanaGroup.N5_GREETINGS },
  { char: 'いってきます', romaji: 'ittekimasu', meaning: 'Tôi đi đây (người đi nói)', row: 'phrase', type: AlphabetType.PHRASE, group: KanaGroup.N5_GREETINGS },
  { char: 'いってらっしゃい', romaji: 'itterasshai', meaning: 'Bạn đi nhé (người ở lại nói)', row: 'phrase', type: AlphabetType.PHRASE, group: KanaGroup.N5_GREETINGS },
  { char: 'ただいま', romaji: 'tadaima', meaning: 'Tôi đã về rồi đây', row: 'phrase', type: AlphabetType.PHRASE, group: KanaGroup.N5_GREETINGS },
  { char: 'おかえりなさい', romaji: 'okaerinasai', meaning: 'Mừng bạn đã về', row: 'phrase', type: AlphabetType.PHRASE, group: KanaGroup.N5_GREETINGS },
];

const N5_COUNTERS: KanaChar[] = [
  { char: 'ひとつ', romaji: 'hitotsu', meaning: '1 cái (chung)', row: 'counter', type: AlphabetType.VOCABULARY, group: KanaGroup.N5_COUNTERS },
  { char: 'ふたつ', romaji: 'futatsu', meaning: '2 cái (chung)', row: 'counter', type: AlphabetType.VOCABULARY, group: KanaGroup.N5_COUNTERS },
  { char: 'みっつ', romaji: 'mittsu', meaning: '3 cái (chung)', row: 'counter', type: AlphabetType.VOCABULARY, group: KanaGroup.N5_COUNTERS },
  { char: 'ひとり', romaji: 'hitori', meaning: '1 người', row: 'counter', type: AlphabetType.VOCABULARY, group: KanaGroup.N5_COUNTERS },
  { char: 'ふたり', romaji: 'futari', meaning: '2 người', row: 'counter', type: AlphabetType.VOCABULARY, group: KanaGroup.N5_COUNTERS },
  { char: 'さんにん', romaji: 'sannin', meaning: '3 người', row: 'counter', type: AlphabetType.VOCABULARY, group: KanaGroup.N5_COUNTERS },
  { char: 'まい', romaji: '-mai', meaning: 'Đếm vật mỏng (giấy, áo)', row: 'counter', type: AlphabetType.VOCABULARY, group: KanaGroup.N5_COUNTERS },
  { char: 'だい', romaji: '-dai', meaning: 'Đếm máy móc/xe cộ', row: 'counter', type: AlphabetType.VOCABULARY, group: KanaGroup.N5_COUNTERS },
  { char: 'さつ', romaji: '-satsu', meaning: 'Đếm sách/vở', row: 'counter', type: AlphabetType.VOCABULARY, group: KanaGroup.N5_COUNTERS },
  { char: 'ほん / ぽん', romaji: '-hon / -pon', meaning: 'Đếm vật dài (bút, chai)', row: 'counter', type: AlphabetType.VOCABULARY, group: KanaGroup.N5_COUNTERS },
];

const N5_KANJI_TIME_DIR: KanaChar[] = [
  { char: '時', romaji: 'ji', meaning: 'Giờ / Thời', row: 'kanji', type: AlphabetType.KANJI, group: KanaGroup.N5_KANJI_TIME_DIR },
  { char: '分', romaji: 'fun / bun', meaning: 'Phút / Phân chia', row: 'kanji', type: AlphabetType.KANJI, group: KanaGroup.N5_KANJI_TIME_DIR },
  { char: '半', romaji: 'han', meaning: 'Một nửa / Rưỡi', row: 'kanji', type: AlphabetType.KANJI, group: KanaGroup.N5_KANJI_TIME_DIR },
  { char: '今', romaji: 'ima / kon', meaning: 'Bây giờ / Kim', row: 'kanji', type: AlphabetType.KANJI, group: KanaGroup.N5_KANJI_TIME_DIR },
  { char: '上', romaji: 'ue / jou', meaning: 'Trên', row: 'kanji', type: AlphabetType.KANJI, group: KanaGroup.N5_KANJI_TIME_DIR },
  { char: '下', romaji: 'shita / ka', meaning: 'Dưới', row: 'kanji', type: AlphabetType.KANJI, group: KanaGroup.N5_KANJI_TIME_DIR },
  { char: '前', romaji: 'mae / zen', meaning: 'Trước', row: 'kanji', type: AlphabetType.KANJI, group: KanaGroup.N5_KANJI_TIME_DIR },
  { char: '後', romaji: 'ushiro / go / ato', meaning: 'Sau', row: 'kanji', type: AlphabetType.KANJI, group: KanaGroup.N5_KANJI_TIME_DIR },
  { char: '左', romaji: 'hidari', meaning: 'Trái', row: 'kanji', type: AlphabetType.KANJI, group: KanaGroup.N5_KANJI_TIME_DIR },
  { char: '右', romaji: 'migi', meaning: 'Phải', row: 'kanji', type: AlphabetType.KANJI, group: KanaGroup.N5_KANJI_TIME_DIR },
  { char: '東', romaji: 'higashi / tou', meaning: 'Đông', row: 'kanji', type: AlphabetType.KANJI, group: KanaGroup.N5_KANJI_TIME_DIR },
  { char: '西', romaji: 'nishi / sei', meaning: 'Tây', row: 'kanji', type: AlphabetType.KANJI, group: KanaGroup.N5_KANJI_TIME_DIR },
  { char: '南', romaji: 'minami / nan', meaning: 'Nam', row: 'kanji', type: AlphabetType.KANJI, group: KanaGroup.N5_KANJI_TIME_DIR },
  { char: '北', romaji: 'kita / hoku', meaning: 'Bắc', row: 'kanji', type: AlphabetType.KANJI, group: KanaGroup.N5_KANJI_TIME_DIR },
];

const N5_FAMILY_COLORS: KanaChar[] = [
  { char: 'ちち', romaji: 'chichi', meaning: 'Bố (của tôi)', row: 'family', type: AlphabetType.VOCABULARY, group: KanaGroup.N5_FAMILY_COLORS },
  { char: 'はは', romaji: 'haha', meaning: 'Mẹ (của tôi)', row: 'family', type: AlphabetType.VOCABULARY, group: KanaGroup.N5_FAMILY_COLORS },
  { char: 'おとうさん', romaji: 'otousan', meaning: 'Bố (người khác)', row: 'family', type: AlphabetType.VOCABULARY, group: KanaGroup.N5_FAMILY_COLORS },
  { char: 'おかあさん', romaji: 'okaasan', meaning: 'Mẹ (người khác)', row: 'family', type: AlphabetType.VOCABULARY, group: KanaGroup.N5_FAMILY_COLORS },
  { char: 'あに', romaji: 'ani', meaning: 'Anh trai (của tôi)', row: 'family', type: AlphabetType.VOCABULARY, group: KanaGroup.N5_FAMILY_COLORS },
  { char: 'あね', romaji: 'ane', meaning: 'Chị gái (của tôi)', row: 'family', type: AlphabetType.VOCABULARY, group: KanaGroup.N5_FAMILY_COLORS },
  { char: 'おとうと', romaji: 'otouto', meaning: 'Em trai', row: 'family', type: AlphabetType.VOCABULARY, group: KanaGroup.N5_FAMILY_COLORS },
  { char: 'いもうと', romaji: 'imouto', meaning: 'Em gái', row: 'family', type: AlphabetType.VOCABULARY, group: KanaGroup.N5_FAMILY_COLORS },
  { char: 'しろい', romaji: 'shiroi', meaning: 'Màu trắng', row: 'color', type: AlphabetType.VOCABULARY, group: KanaGroup.N5_FAMILY_COLORS },
  { char: 'くろい', romaji: 'kuroi', meaning: 'Màu đen', row: 'color', type: AlphabetType.VOCABULARY, group: KanaGroup.N5_FAMILY_COLORS },
  { char: 'あかい', romaji: 'akai', meaning: 'Màu đỏ', row: 'color', type: AlphabetType.VOCABULARY, group: KanaGroup.N5_FAMILY_COLORS },
  { char: 'あおい', romaji: 'aoi', meaning: 'Màu xanh dương', row: 'color', type: AlphabetType.VOCABULARY, group: KanaGroup.N5_FAMILY_COLORS },
];

const N5_KANJI_SCHOOL_LIFE: KanaChar[] = [
  { char: '学', romaji: 'gaku / mana', meaning: 'Học', row: 'kanji', type: AlphabetType.KANJI, group: KanaGroup.N5_KANJI_SCHOOL_LIFE },
  { char: '校', romaji: 'kou', meaning: 'Trường học', row: 'kanji', type: AlphabetType.KANJI, group: KanaGroup.N5_KANJI_SCHOOL_LIFE },
  { char: '先', romaji: 'sen / saki', meaning: 'Trước / Tiên', row: 'kanji', type: AlphabetType.KANJI, group: KanaGroup.N5_KANJI_SCHOOL_LIFE },
  { char: '生', romaji: 'sei / i', meaning: 'Sinh / Sống', row: 'kanji', type: AlphabetType.KANJI, group: KanaGroup.N5_KANJI_SCHOOL_LIFE },
  { char: '本', romaji: 'hon / moto', meaning: 'Sách / Gốc', row: 'kanji', type: AlphabetType.KANJI, group: KanaGroup.N5_KANJI_SCHOOL_LIFE },
  { char: '文', romaji: 'bun / fumi', meaning: 'Văn chương', row: 'kanji', type: AlphabetType.KANJI, group: KanaGroup.N5_KANJI_SCHOOL_LIFE },
  { char: '字', romaji: 'ji', meaning: 'Chữ', row: 'kanji', type: AlphabetType.KANJI, group: KanaGroup.N5_KANJI_SCHOOL_LIFE },
  { char: '名', romaji: 'mei / na', meaning: 'Tên / Danh', row: 'kanji', type: AlphabetType.KANJI, group: KanaGroup.N5_KANJI_SCHOOL_LIFE },
  { char: '目', romaji: 'moku / me', meaning: 'Mắt', row: 'kanji', type: AlphabetType.KANJI, group: KanaGroup.N5_KANJI_SCHOOL_LIFE },
  { char: '耳', romaji: 'ji / mimi', meaning: 'Tai', row: 'kanji', type: AlphabetType.KANJI, group: KanaGroup.N5_KANJI_SCHOOL_LIFE },
  { char: '手', romaji: 'shu / te', meaning: 'Tay', row: 'kanji', type: AlphabetType.KANJI, group: KanaGroup.N5_KANJI_SCHOOL_LIFE },
  { char: '足', romaji: 'soku / ashi', meaning: 'Chân', row: 'kanji', type: AlphabetType.KANJI, group: KanaGroup.N5_KANJI_SCHOOL_LIFE },
  { char: '雨', romaji: 'u / ame', meaning: 'Mưa', row: 'kanji', type: AlphabetType.KANJI, group: KanaGroup.N5_KANJI_SCHOOL_LIFE },
  { char: '竹', romaji: 'chiku / take', meaning: 'Tre', row: 'kanji', type: AlphabetType.KANJI, group: KanaGroup.N5_KANJI_SCHOOL_LIFE },
  { char: '米', romaji: 'bei / kome', meaning: 'Gạo', row: 'kanji', type: AlphabetType.KANJI, group: KanaGroup.N5_KANJI_SCHOOL_LIFE },
  { char: '貝', romaji: 'kai', meaning: 'Vỏ sò', row: 'kanji', type: AlphabetType.KANJI, group: KanaGroup.N5_KANJI_SCHOOL_LIFE },
  { char: '石', romaji: 'seki / ishi', meaning: 'Đá', row: 'kanji', type: AlphabetType.KANJI, group: KanaGroup.N5_KANJI_SCHOOL_LIFE },
  { char: '糸', romaji: 'shi / ito', meaning: 'Sợi chỉ', row: 'kanji', type: AlphabetType.KANJI, group: KanaGroup.N5_KANJI_SCHOOL_LIFE },
];

export const KANA_DATA = {
  [KanaGroup.HIRAGANA_BASIC]: HIRAGANA_BASIC,
  [KanaGroup.HIRAGANA_DAKUTEN]: HIRAGANA_DAKUTEN,
  [KanaGroup.HIRAGANA_YOON]: HIRAGANA_YOON,
  [KanaGroup.SPECIAL_SOUNDS]: SPECIAL_SOUNDS,
  [KanaGroup.KATAKANA_BASIC]: KATAKANA_BASIC,
  [KanaGroup.KATAKANA_DAKUTEN]: KATAKANA_DAKUTEN,
  [KanaGroup.ALL_BASIC]: [...HIRAGANA_BASIC, ...KATAKANA_BASIC],
  [KanaGroup.NUMBERS]: NUMBERS,
  [KanaGroup.DATES]: DATES,
  [KanaGroup.N5_PRONOUNS]: N5_PRONOUNS,
  [KanaGroup.N5_ADJECTIVES]: N5_ADJECTIVES,
  [KanaGroup.N5_VERBS]: N5_VERBS,
  [KanaGroup.N5_KANJI_BASIC]: N5_KANJI_BASIC,
  [KanaGroup.N5_PARTICLES]: N5_PARTICLES,
  // New
  [KanaGroup.N5_GREETINGS]: N5_GREETINGS,
  [KanaGroup.N5_COUNTERS]: N5_COUNTERS,
  [KanaGroup.N5_KANJI_TIME_DIR]: N5_KANJI_TIME_DIR,
  [KanaGroup.N5_FAMILY_COLORS]: N5_FAMILY_COLORS,
  [KanaGroup.N5_KANJI_SCHOOL_LIFE]: N5_KANJI_SCHOOL_LIFE,
};
